import { forwardRef, type ComponentType, type ForwardRefExoticComponent } from "react";
import type { StyleProp, TextStyle, ViewStyle } from "react-native";
import type { IconProps, IconWeight } from "phosphor-react-native";
import { ArchiveIcon as PhArchive } from "phosphor-react-native/src/icons/Archive";
import { ArrowClockwiseIcon as PhArrowClockwise } from "phosphor-react-native/src/icons/ArrowClockwise";
import { ArrowDownIcon as PhArrowDown } from "phosphor-react-native/src/icons/ArrowDown";
import { ArrowElbowDownLeftIcon as PhArrowElbowDownLeft } from "phosphor-react-native/src/icons/ArrowElbowDownLeft";
import { ArrowLeftIcon as PhArrowLeft } from "phosphor-react-native/src/icons/ArrowLeft";
import { ArrowLineDownIcon as PhArrowLineDown } from "phosphor-react-native/src/icons/ArrowLineDown";
import { ArrowLineLeftIcon as PhArrowLineLeft } from "phosphor-react-native/src/icons/ArrowLineLeft";
import { ArrowLineRightIcon as PhArrowLineRight } from "phosphor-react-native/src/icons/ArrowLineRight";
import { ArrowLineUpIcon as PhArrowLineUp } from "phosphor-react-native/src/icons/ArrowLineUp";
import { ArrowRightIcon as PhArrowRight } from "phosphor-react-native/src/icons/ArrowRight";
import { ArrowSquareOutIcon as PhArrowSquareOut } from "phosphor-react-native/src/icons/ArrowSquareOut";
import { ArrowUDownLeftIcon as PhArrowUDownLeft } from "phosphor-react-native/src/icons/ArrowUDownLeft";
import { ArrowUUpLeftIcon as PhArrowUUpLeft } from "phosphor-react-native/src/icons/ArrowUUpLeft";
import { ArrowUpIcon as PhArrowUp } from "phosphor-react-native/src/icons/ArrowUp";
import { ArrowUpRightIcon as PhArrowUpRight } from "phosphor-react-native/src/icons/ArrowUpRight";
import { ArrowsClockwiseIcon as PhArrowsClockwise } from "phosphor-react-native/src/icons/ArrowsClockwise";
import { ArrowsCounterClockwiseIcon as PhArrowsCounterClockwise } from "phosphor-react-native/src/icons/ArrowsCounterClockwise";
import { ArrowsDownUpIcon as PhArrowsDownUp } from "phosphor-react-native/src/icons/ArrowsDownUp";
import { ArrowsInIcon as PhArrowsIn } from "phosphor-react-native/src/icons/ArrowsIn";
import { ArrowsInLineVerticalIcon as PhArrowsInLineVertical } from "phosphor-react-native/src/icons/ArrowsInLineVertical";
import { ArrowsOutIcon as PhArrowsOut } from "phosphor-react-native/src/icons/ArrowsOut";
import { ArrowsOutCardinalIcon as PhArrowsOutCardinal } from "phosphor-react-native/src/icons/ArrowsOutCardinal";
import { ArrowsOutLineVerticalIcon as PhArrowsOutLineVertical } from "phosphor-react-native/src/icons/ArrowsOutLineVertical";
import { BellIcon as PhBell } from "phosphor-react-native/src/icons/Bell";
import { BookOpenIcon as PhBookOpen } from "phosphor-react-native/src/icons/BookOpen";
import { BrainIcon as PhBrain } from "phosphor-react-native/src/icons/Brain";
import { BugIcon as PhBug } from "phosphor-react-native/src/icons/Bug";
import { CalendarDotsIcon as PhCalendarDots } from "phosphor-react-native/src/icons/CalendarDots";
import { CameraIcon as PhCamera } from "phosphor-react-native/src/icons/Camera";
import { CaretDownIcon as PhCaretDown } from "phosphor-react-native/src/icons/CaretDown";
import { CaretLeftIcon as PhCaretLeft } from "phosphor-react-native/src/icons/CaretLeft";
import { CaretRightIcon as PhCaretRight } from "phosphor-react-native/src/icons/CaretRight";
import { CaretUpIcon as PhCaretUp } from "phosphor-react-native/src/icons/CaretUp";
import { ChatCenteredTextIcon as PhChatCenteredText } from "phosphor-react-native/src/icons/ChatCenteredText";
import { ChatCircleIcon as PhChatCircle } from "phosphor-react-native/src/icons/ChatCircle";
import { ChatTeardropTextIcon as PhChatTeardropText } from "phosphor-react-native/src/icons/ChatTeardropText";
import { CheckIcon as PhCheck } from "phosphor-react-native/src/icons/Check";
import { CheckCircleIcon as PhCheckCircle } from "phosphor-react-native/src/icons/CheckCircle";
import { CheckSquareIcon as PhCheckSquare } from "phosphor-react-native/src/icons/CheckSquare";
import { CircleIcon as PhCircle } from "phosphor-react-native/src/icons/Circle";
import { CircleDashedIcon as PhCircleDashed } from "phosphor-react-native/src/icons/CircleDashed";
import { ClipboardIcon as PhClipboard } from "phosphor-react-native/src/icons/Clipboard";
import { ClockIcon as PhClock } from "phosphor-react-native/src/icons/Clock";
import { ClockCounterClockwiseIcon as PhClockCounterClockwise } from "phosphor-react-native/src/icons/ClockCounterClockwise";
import { ClosedCaptioningIcon as PhClosedCaptioning } from "phosphor-react-native/src/icons/ClosedCaptioning";
import { CloudIcon as PhCloud } from "phosphor-react-native/src/icons/Cloud";
import { CodeIcon as PhCode } from "phosphor-react-native/src/icons/Code";
import { CodeBlockIcon as PhCodeBlock } from "phosphor-react-native/src/icons/CodeBlock";
import { ColumnsIcon as PhColumns } from "phosphor-react-native/src/icons/Columns";
import { CompassIcon as PhCompass } from "phosphor-react-native/src/icons/Compass";
import { CopyIcon as PhCopy } from "phosphor-react-native/src/icons/Copy";
import { CopySimpleIcon as PhCopySimple } from "phosphor-react-native/src/icons/CopySimple";
import { CpuIcon as PhCpu } from "phosphor-react-native/src/icons/Cpu";
import { CrosshairIcon as PhCrosshair } from "phosphor-react-native/src/icons/Crosshair";
import { CubeIcon as PhCube } from "phosphor-react-native/src/icons/Cube";
import { CursorIcon as PhCursor } from "phosphor-react-native/src/icons/Cursor";
import { DatabaseIcon as PhDatabase } from "phosphor-react-native/src/icons/Database";
import { DeviceMobileIcon as PhDeviceMobile } from "phosphor-react-native/src/icons/DeviceMobile";
import { DeviceTabletIcon as PhDeviceTablet } from "phosphor-react-native/src/icons/DeviceTablet";
import { DotOutlineIcon as PhDotOutline } from "phosphor-react-native/src/icons/DotOutline";
import { DotsThreeIcon as PhDotsThree } from "phosphor-react-native/src/icons/DotsThree";
import { DotsThreeVerticalIcon as PhDotsThreeVertical } from "phosphor-react-native/src/icons/DotsThreeVertical";
import { DownloadSimpleIcon as PhDownloadSimple } from "phosphor-react-native/src/icons/DownloadSimple";
import { EyeIcon as PhEye } from "phosphor-react-native/src/icons/Eye";
import { EyeSlashIcon as PhEyeSlash } from "phosphor-react-native/src/icons/EyeSlash";
import { FeatherIcon as PhFeather } from "phosphor-react-native/src/icons/Feather";
import { FileIcon as PhFile } from "phosphor-react-native/src/icons/File";
import { FileArrowUpIcon as PhFileArrowUp } from "phosphor-react-native/src/icons/FileArrowUp";
import { FilePlusIcon as PhFilePlus } from "phosphor-react-native/src/icons/FilePlus";
import { FileTextIcon as PhFileText } from "phosphor-react-native/src/icons/FileText";
import { FileXIcon as PhFileX } from "phosphor-react-native/src/icons/FileX";
import { FilesIcon as PhFiles } from "phosphor-react-native/src/icons/Files";
import { FlaskIcon as PhFlask } from "phosphor-react-native/src/icons/Flask";
import { FlowArrowIcon as PhFlowArrow } from "phosphor-react-native/src/icons/FlowArrow";
import { FolderIcon as PhFolder } from "phosphor-react-native/src/icons/Folder";
import { FolderMinusIcon as PhFolderMinus } from "phosphor-react-native/src/icons/FolderMinus";
import { FolderOpenIcon as PhFolderOpen } from "phosphor-react-native/src/icons/FolderOpen";
import { FolderPlusIcon as PhFolderPlus } from "phosphor-react-native/src/icons/FolderPlus";
import { FunnelIcon as PhFunnel } from "phosphor-react-native/src/icons/Funnel";
import { GaugeIcon as PhGauge } from "phosphor-react-native/src/icons/Gauge";
import { GearIcon as PhGear } from "phosphor-react-native/src/icons/Gear";
import { GiftIcon as PhGift } from "phosphor-react-native/src/icons/Gift";
import { GitBranchIcon as PhGitBranch } from "phosphor-react-native/src/icons/GitBranch";
import { GitCommitIcon as PhGitCommit } from "phosphor-react-native/src/icons/GitCommit";
import { GitDiffIcon as PhGitDiff } from "phosphor-react-native/src/icons/GitDiff";
import { GitForkIcon as PhGitFork } from "phosphor-react-native/src/icons/GitFork";
import { GitMergeIcon as PhGitMerge } from "phosphor-react-native/src/icons/GitMerge";
import { GitPullRequestIcon as PhGitPullRequest } from "phosphor-react-native/src/icons/GitPullRequest";
import { GithubLogoIcon as PhGithubLogo } from "phosphor-react-native/src/icons/GithubLogo";
import { GlobeIcon as PhGlobe } from "phosphor-react-native/src/icons/Globe";
import { GlobeSimpleIcon as PhGlobeSimple } from "phosphor-react-native/src/icons/GlobeSimple";
import { GraphIcon as PhGraph } from "phosphor-react-native/src/icons/Graph";
import { HammerIcon as PhHammer } from "phosphor-react-native/src/icons/Hammer";
import { HardDriveIcon as PhHardDrive } from "phosphor-react-native/src/icons/HardDrive";
import { HardDrivesIcon as PhHardDrives } from "phosphor-react-native/src/icons/HardDrives";
import { HeartIcon as PhHeart } from "phosphor-react-native/src/icons/Heart";
import { HouseIcon as PhHouse } from "phosphor-react-native/src/icons/House";
import { ImageIcon as PhImage } from "phosphor-react-native/src/icons/Image";
import { InfoIcon as PhInfo } from "phosphor-react-native/src/icons/Info";
import { KeyboardIcon as PhKeyboard } from "phosphor-react-native/src/icons/Keyboard";
import { LayoutIcon as PhLayout } from "phosphor-react-native/src/icons/Layout";
import { LightningIcon as PhLightning } from "phosphor-react-native/src/icons/Lightning";
import { LinkIcon as PhLink } from "phosphor-react-native/src/icons/Link";
import { LinkBreakIcon as PhLinkBreak } from "phosphor-react-native/src/icons/LinkBreak";
import { LinkSimpleIcon as PhLinkSimple } from "phosphor-react-native/src/icons/LinkSimple";
import { LockIcon as PhLock } from "phosphor-react-native/src/icons/Lock";
import { ListChecksIcon as PhListChecks } from "phosphor-react-native/src/icons/ListChecks";
import { MagnifyingGlassIcon as PhMagnifyingGlass } from "phosphor-react-native/src/icons/MagnifyingGlass";
import { MagnifyingGlassMinusIcon as PhMagnifyingGlassMinus } from "phosphor-react-native/src/icons/MagnifyingGlassMinus";
import { MagnifyingGlassPlusIcon as PhMagnifyingGlassPlus } from "phosphor-react-native/src/icons/MagnifyingGlassPlus";
import { MicrophoneIcon as PhMicrophone } from "phosphor-react-native/src/icons/Microphone";
import { MicrophoneSlashIcon as PhMicrophoneSlash } from "phosphor-react-native/src/icons/MicrophoneSlash";
import { MicrophoneStageIcon as PhMicrophoneStage } from "phosphor-react-native/src/icons/MicrophoneStage";
import { MicroscopeIcon as PhMicroscope } from "phosphor-react-native/src/icons/Microscope";
import { MinusSquareIcon as PhMinusSquare } from "phosphor-react-native/src/icons/MinusSquare";
import { MonitorIcon as PhMonitor } from "phosphor-react-native/src/icons/Monitor";
import { MoonIcon as PhMoon } from "phosphor-react-native/src/icons/Moon";
import { NotePencilIcon as PhNotePencil } from "phosphor-react-native/src/icons/NotePencil";
import { PackageIcon as PhPackage } from "phosphor-react-native/src/icons/Package";
import { PaletteIcon as PhPalette } from "phosphor-react-native/src/icons/Palette";
import { PaperclipIcon as PhPaperclip } from "phosphor-react-native/src/icons/Paperclip";
import { ParagraphIcon as PhParagraph } from "phosphor-react-native/src/icons/Paragraph";
import { PauseIcon as PhPause } from "phosphor-react-native/src/icons/Pause";
import { PencilSimpleIcon as PhPencilSimple } from "phosphor-react-native/src/icons/PencilSimple";
import { PlayIcon as PhPlay } from "phosphor-react-native/src/icons/Play";
import { PlugIcon as PhPlug } from "phosphor-react-native/src/icons/Plug";
import { PlusIcon as PhPlus } from "phosphor-react-native/src/icons/Plus";
import { PlusSquareIcon as PhPlusSquare } from "phosphor-react-native/src/icons/PlusSquare";
import { ProhibitIcon as PhProhibit } from "phosphor-react-native/src/icons/Prohibit";
import { PulseIcon as PhPulse } from "phosphor-react-native/src/icons/Pulse";
import { PushPinIcon as PhPushPin } from "phosphor-react-native/src/icons/PushPin";
import { PushPinSlashIcon as PhPushPinSlash } from "phosphor-react-native/src/icons/PushPinSlash";
import { PuzzlePieceIcon as PhPuzzlePiece } from "phosphor-react-native/src/icons/PuzzlePiece";
import { QrCodeIcon as PhQrCode } from "phosphor-react-native/src/icons/QrCode";
import { QuestionIcon as PhQuestion } from "phosphor-react-native/src/icons/Question";
import { RadioButtonIcon as PhRadioButton } from "phosphor-react-native/src/icons/RadioButton";
import { RobotIcon as PhRobot } from "phosphor-react-native/src/icons/Robot";
import { RocketIcon as PhRocket } from "phosphor-react-native/src/icons/Rocket";
import { RowsIcon as PhRows } from "phosphor-react-native/src/icons/Rows";
import { ScanIcon as PhScan } from "phosphor-react-native/src/icons/Scan";
import { ScissorsIcon as PhScissors } from "phosphor-react-native/src/icons/Scissors";
import { ShieldIcon as PhShield } from "phosphor-react-native/src/icons/Shield";
import { ShieldCheckIcon as PhShieldCheck } from "phosphor-react-native/src/icons/ShieldCheck";
import { ShieldCheckeredIcon as PhShieldCheckered } from "phosphor-react-native/src/icons/ShieldCheckered";
import { ShieldChevronIcon as PhShieldChevron } from "phosphor-react-native/src/icons/ShieldChevron";
import { ShieldPlusIcon as PhShieldPlus } from "phosphor-react-native/src/icons/ShieldPlus";
import { ShieldSlashIcon as PhShieldSlash } from "phosphor-react-native/src/icons/ShieldSlash";
import { ShieldWarningIcon as PhShieldWarning } from "phosphor-react-native/src/icons/ShieldWarning";
import { SidebarIcon as PhSidebar } from "phosphor-react-native/src/icons/Sidebar";
import { SidebarSimpleIcon as PhSidebarSimple } from "phosphor-react-native/src/icons/SidebarSimple";
import { SlidersHorizontalIcon as PhSlidersHorizontal } from "phosphor-react-native/src/icons/SlidersHorizontal";
import { SparkleIcon as PhSparkle } from "phosphor-react-native/src/icons/Sparkle";
import { SquareIcon as PhSquare } from "phosphor-react-native/src/icons/Square";
import { SquaresFourIcon as PhSquaresFour } from "phosphor-react-native/src/icons/SquaresFour";
import { StackIcon as PhStack } from "phosphor-react-native/src/icons/Stack";
import { StarIcon as PhStar } from "phosphor-react-native/src/icons/Star";
import { StethoscopeIcon as PhStethoscope } from "phosphor-react-native/src/icons/Stethoscope";
import { SunIcon as PhSun } from "phosphor-react-native/src/icons/Sun";
import { TagIcon as PhTag } from "phosphor-react-native/src/icons/Tag";
import { TerminalIcon as PhTerminal } from "phosphor-react-native/src/icons/Terminal";
import { TerminalWindowIcon as PhTerminalWindow } from "phosphor-react-native/src/icons/TerminalWindow";
import { TestTubeIcon as PhTestTube } from "phosphor-react-native/src/icons/TestTube";
import { TextAlignJustifyIcon as PhTextAlignJustify } from "phosphor-react-native/src/icons/TextAlignJustify";
import { TextTIcon as PhTextT } from "phosphor-react-native/src/icons/TextT";
import { TrashIcon as PhTrash } from "phosphor-react-native/src/icons/Trash";
import { TrayIcon as PhTray } from "phosphor-react-native/src/icons/Tray";
import { TreeStructureIcon as PhTreeStructure } from "phosphor-react-native/src/icons/TreeStructure";
import { UploadSimpleIcon as PhUploadSimple } from "phosphor-react-native/src/icons/UploadSimple";
import { UserIcon as PhUser } from "phosphor-react-native/src/icons/User";
import { WarningIcon as PhWarning } from "phosphor-react-native/src/icons/Warning";
import { WarningCircleIcon as PhWarningCircle } from "phosphor-react-native/src/icons/WarningCircle";
import { WaveformIcon as PhWaveform } from "phosphor-react-native/src/icons/Waveform";
import { WrenchIcon as PhWrench } from "phosphor-react-native/src/icons/Wrench";
import { XIcon as PhX } from "phosphor-react-native/src/icons/X";
import { XCircleIcon as PhXCircle } from "phosphor-react-native/src/icons/XCircle";
import { XSquareIcon as PhXSquare } from "phosphor-react-native/src/icons/XSquare";
import { UsersThreeIcon as PhUsersThree } from "phosphor-react-native/src/icons/UsersThree";

export interface UiIconProps {
  size?: number;
  color?: string;
  strokeWidth?: number | string;
  fill?: string;
  absoluteStrokeWidth?: boolean;
  opacity?: number;
  style?: StyleProp<ViewStyle | Omit<TextStyle, "cursor">>;
  testID?: string;
  accessibilityLabel?: string;
}

export type LucideIcon = ForwardRefExoticComponent<UiIconProps>;

function weightFor(props: UiIconProps): IconWeight {
  if (props.fill && props.fill !== "none" && props.fill !== "transparent") return "fill";
  return Number(props.strokeWidth ?? 2) >= 2.5 ? "bold" : "regular";
}

function uiIcon(Icon: ComponentType<IconProps>, name: string): LucideIcon {
  const UiIcon = forwardRef<unknown, UiIconProps>(function UiIcon(props, _ref) {
    const {
      strokeWidth: _strokeWidth,
      fill: _fill,
      absoluteStrokeWidth: _absolute,
      uniProps: _uniProps,
      opacity,
      style,
      ...rest
    } = props as UiIconProps & { uniProps?: unknown };
    return (
      <Icon
        {...rest}
        style={opacity === undefined ? style : [style, { opacity }]}
        weight={weightFor(props)}
      />
    );
  });
  UiIcon.displayName = name;
  return UiIcon;
}

export const Activity = uiIcon(PhPulse, "Activity");
export const AlertCircle = uiIcon(PhWarningCircle, "AlertCircle");
export const AlertTriangle = uiIcon(PhWarning, "AlertTriangle");
export const AlignJustify = uiIcon(PhTextAlignJustify, "AlignJustify");
export const Archive = uiIcon(PhArchive, "Archive");
export const ArrowDown = uiIcon(PhArrowDown, "ArrowDown");
export const ArrowDownToLine = uiIcon(PhArrowLineDown, "ArrowDownToLine");
export const ArrowDownUp = uiIcon(PhArrowsDownUp, "ArrowDownUp");
export const ArrowLeft = uiIcon(PhArrowLeft, "ArrowLeft");
export const ArrowLeftToLine = uiIcon(PhArrowLineLeft, "ArrowLeftToLine");
export const ArrowRight = uiIcon(PhArrowRight, "ArrowRight");
export const ArrowRightToLine = uiIcon(PhArrowLineRight, "ArrowRightToLine");
export const ArrowUp = uiIcon(PhArrowUp, "ArrowUp");
export const ArrowUpRight = uiIcon(PhArrowUpRight, "ArrowUpRight");
export const ArrowUpToLine = uiIcon(PhArrowLineUp, "ArrowUpToLine");
export const AudioLines = uiIcon(PhWaveform, "AudioLines");
export const Bell = uiIcon(PhBell, "Bell");
export const Blocks = uiIcon(PhSquaresFour, "Blocks");
export const BookOpen = uiIcon(PhBookOpen, "BookOpen");
export const Bot = uiIcon(PhRobot, "Bot");
export const Boxes = uiIcon(PhCube, "Boxes");
export const Brain = uiIcon(PhBrain, "Brain");
export const Bug = uiIcon(PhBug, "Bug");
export const CalendarClock = uiIcon(PhCalendarDots, "CalendarClock");
export const Camera = uiIcon(PhCamera, "Camera");
export const Captions = uiIcon(PhClosedCaptioning, "Captions");
export const Check = uiIcon(PhCheck, "Check");
export const CheckCircle = uiIcon(PhCheckCircle, "CheckCircle");
export const CheckCircle2 = uiIcon(PhCheckCircle, "CheckCircle2");
export const CheckSquare = uiIcon(PhCheckSquare, "CheckSquare");
export const ChevronDown = uiIcon(PhCaretDown, "ChevronDown");
export const ChevronLeft = uiIcon(PhCaretLeft, "ChevronLeft");
export const ChevronRight = uiIcon(PhCaretRight, "ChevronRight");
export const ChevronUp = uiIcon(PhCaretUp, "ChevronUp");
export const Circle = uiIcon(PhCircle, "Circle");
export const CircleAlert = uiIcon(PhWarningCircle, "CircleAlert");
export const CircleCheck = uiIcon(PhCheckCircle, "CircleCheck");
export const CircleDashed = uiIcon(PhCircleDashed, "CircleDashed");
export const CircleDot = uiIcon(PhRadioButton, "CircleDot");
export const CircleHelp = uiIcon(PhQuestion, "CircleHelp");
export const CircleSlash = uiIcon(PhProhibit, "CircleSlash");
export const CircleX = uiIcon(PhXCircle, "CircleX");
export const ClipboardPaste = uiIcon(PhClipboard, "ClipboardPaste");
export const Clock = uiIcon(PhClock, "Clock");
export const Cloud = uiIcon(PhCloud, "Cloud");
export const Code = uiIcon(PhCode, "Code");
export const Code2 = uiIcon(PhCode, "Code2");
export const Columns2 = uiIcon(PhColumns, "Columns2");
export const Compass = uiIcon(PhCompass, "Compass");
export const Copy = uiIcon(PhCopy, "Copy");
export const CopyPlus = uiIcon(PhCopySimple, "CopyPlus");
export const CopyX = uiIcon(PhXSquare, "CopyX");
export const CornerDownLeft = uiIcon(PhArrowElbowDownLeft, "CornerDownLeft");
export const Cpu = uiIcon(PhCpu, "Cpu");
export const Database = uiIcon(PhDatabase, "Database");
export const Diff = uiIcon(PhGitDiff, "Diff");
export const Download = uiIcon(PhDownloadSimple, "Download");
export const Ellipsis = uiIcon(PhDotsThree, "Ellipsis");
export const ExternalLink = uiIcon(PhArrowSquareOut, "ExternalLink");
export const Eye = uiIcon(PhEye, "Eye");
export const EyeOff = uiIcon(PhEyeSlash, "EyeOff");
export const Feather = uiIcon(PhFeather, "Feather");
export const File = uiIcon(PhFile, "File");
export const FileDiff = uiIcon(PhGitDiff, "FileDiff");
export const FilePlus = uiIcon(PhFilePlus, "FilePlus");
export const Files = uiIcon(PhFiles, "Files");
export const FileSymlink = uiIcon(PhFileArrowUp, "FileSymlink");
export const FileText = uiIcon(PhFileText, "FileText");
export const FileWarning = uiIcon(PhFileX, "FileWarning");
export const FlaskConical = uiIcon(PhFlask, "FlaskConical");
export const Focus = uiIcon(PhCrosshair, "Focus");
export const Folder = uiIcon(PhFolder, "Folder");
export const FolderGit2 = uiIcon(PhGitFork, "FolderGit2");
export const FolderMinus = uiIcon(PhFolderMinus, "FolderMinus");
export const FolderOpen = uiIcon(PhFolderOpen, "FolderOpen");
export const FolderPlus = uiIcon(PhFolderPlus, "FolderPlus");
export const FolderTree = uiIcon(PhTreeStructure, "FolderTree");
export const Gauge = uiIcon(PhGauge, "Gauge");
export const CircleGauge = uiIcon(PhGauge, "CircleGauge");
export const Gift = uiIcon(PhGift, "Gift");
export const GitBranch = uiIcon(PhGitBranch, "GitBranch");
export const GitCommitHorizontal = uiIcon(PhGitCommit, "GitCommitHorizontal");
export const GitCompareArrows = uiIcon(PhGitDiff, "GitCompareArrows");
export const Github = uiIcon(PhGithubLogo, "Github");
export const GitMerge = uiIcon(PhGitMerge, "GitMerge");
export const GitPullRequest = uiIcon(PhGitPullRequest, "GitPullRequest");
export const GitPullRequestClosed = uiIcon(PhGitPullRequest, "GitPullRequestClosed");
export const GitPullRequestDraft = uiIcon(PhGitPullRequest, "GitPullRequestDraft");
export const Globe = uiIcon(PhGlobe, "Globe");
export const Globe2 = uiIcon(PhGlobeSimple, "Globe2");
export const Hammer = uiIcon(PhHammer, "Hammer");
export const HardDrive = uiIcon(PhHardDrive, "HardDrive");
export const Heart = uiIcon(PhHeart, "Heart");
export const History = uiIcon(PhClockCounterClockwise, "History");
export const Home = uiIcon(PhHouse, "Home");
export const Image = uiIcon(PhImage, "Image");
export const Import = uiIcon(PhDownloadSimple, "Import");
export const Inbox = uiIcon(PhTray, "Inbox");
export const Info = uiIcon(PhInfo, "Info");
export const Keyboard = uiIcon(PhKeyboard, "Keyboard");
export const KeyboardOff = uiIcon(PhKeyboard, "KeyboardOff");
export const Layers = uiIcon(PhStack, "Layers");
export const Link = uiIcon(PhLink, "Link");
export const Link2 = uiIcon(PhLinkSimple, "Link2");
export const Lock = uiIcon(PhLock, "Lock");
export const ListChecks = uiIcon(PhListChecks, "ListChecks");
export const ListChevronsDownUp = uiIcon(PhArrowsInLineVertical, "ListChevronsDownUp");
export const ListChevronsUpDown = uiIcon(PhArrowsOutLineVertical, "ListChevronsUpDown");
export const ListFilter = uiIcon(PhFunnel, "ListFilter");
export const ListTodo = uiIcon(PhListChecks, "ListTodo");
export const Maximize = uiIcon(PhArrowsOut, "Maximize");
export const Maximize2 = uiIcon(PhArrowsOut, "Maximize2");
export const MessageCircle = uiIcon(PhChatCircle, "MessageCircle");
export const Users = uiIcon(PhUsersThree, "Users");
export const MessageSquare = uiIcon(PhChatCenteredText, "MessageSquare");
export const MessageSquareCode = uiIcon(PhCodeBlock, "MessageSquareCode");
export const MessageSquarePlus = uiIcon(PhChatTeardropText, "MessageSquarePlus");
export const Mic = uiIcon(PhMicrophone, "Mic");
export const MicOff = uiIcon(PhMicrophoneSlash, "MicOff");
export const Microscope = uiIcon(PhMicroscope, "Microscope");
export const MicVocal = uiIcon(PhMicrophoneStage, "MicVocal");
export const Minimize = uiIcon(PhArrowsIn, "Minimize");
export const Monitor = uiIcon(PhMonitor, "Monitor");
export const Moon = uiIcon(PhMoon, "Moon");
export const MoreHorizontal = uiIcon(PhDotsThree, "MoreHorizontal");
export const MoreVertical = uiIcon(PhDotsThreeVertical, "MoreVertical");
export const MousePointer2 = uiIcon(PhCursor, "MousePointer2");
export const Move = uiIcon(PhArrowsOutCardinal, "Move");
export const Network = uiIcon(PhGraph, "Network");
export const Package = uiIcon(PhPackage, "Package");
export const PackagePlus = uiIcon(PhPackage, "PackagePlus");
export const Palette = uiIcon(PhPalette, "Palette");
export const PanelLeft = uiIcon(PhSidebar, "PanelLeft");
export const PanelRight = uiIcon(PhSidebarSimple, "PanelRight");
export const PanelsTopLeft = uiIcon(PhLayout, "PanelsTopLeft");
export const Paperclip = uiIcon(PhPaperclip, "Paperclip");
export const Pause = uiIcon(PhPause, "Pause");
export const Pencil = uiIcon(PhPencilSimple, "Pencil");
export const Pilcrow = uiIcon(PhParagraph, "Pilcrow");
export const Pin = uiIcon(PhPushPin, "Pin");
export const PinOff = uiIcon(PhPushPinSlash, "PinOff");
export const Play = uiIcon(PhPlay, "Play");
export const Plug = uiIcon(PhPlug, "Plug");
export const Plus = uiIcon(PhPlus, "Plus");
export const Puzzle = uiIcon(PhPuzzlePiece, "Puzzle");
export const QrCode = uiIcon(PhQrCode, "QrCode");
export const RefreshCcw = uiIcon(PhArrowsCounterClockwise, "RefreshCcw");
export const RefreshCw = uiIcon(PhArrowsClockwise, "RefreshCw");
export const Rocket = uiIcon(PhRocket, "Rocket");
export const RotateCw = uiIcon(PhArrowClockwise, "RotateCw");
export const Rows2 = uiIcon(PhRows, "Rows2");
export const Scan = uiIcon(PhScan, "Scan");
export const ScanSearch = uiIcon(PhScan, "ScanSearch");
export const Scissors = uiIcon(PhScissors, "Scissors");
export const Search = uiIcon(PhMagnifyingGlass, "Search");
export const Server = uiIcon(PhHardDrives, "Server");
export const Settings = uiIcon(PhGear, "Settings");
export const Settings2 = uiIcon(PhSlidersHorizontal, "Settings2");
export const Shield = uiIcon(PhShield, "Shield");
export const ShieldAlert = uiIcon(PhShieldWarning, "ShieldAlert");
export const ShieldCheck = uiIcon(PhShieldCheck, "ShieldCheck");
export const ShieldEllipsis = uiIcon(PhShieldChevron, "ShieldEllipsis");
export const ShieldOff = uiIcon(PhShieldSlash, "ShieldOff");
export const ShieldPlus = uiIcon(PhShieldPlus, "ShieldPlus");
export const ShieldQuestionMark = uiIcon(PhShieldCheckered, "ShieldQuestionMark");
export const Smartphone = uiIcon(PhDeviceMobile, "Smartphone");
export const Sparkles = uiIcon(PhSparkle, "Sparkles");
export const Split = uiIcon(PhColumns, "Split");
export const Square = uiIcon(PhSquare, "Square");
export const SquareDot = uiIcon(PhDotOutline, "SquareDot");
export const SquareMinus = uiIcon(PhMinusSquare, "SquareMinus");
export const SquarePen = uiIcon(PhNotePencil, "SquarePen");
export const SquarePlus = uiIcon(PhPlusSquare, "SquarePlus");
export const SquareTerminal = uiIcon(PhTerminalWindow, "SquareTerminal");
export const Star = uiIcon(PhStar, "Star");
export const Stethoscope = uiIcon(PhStethoscope, "Stethoscope");
export const Sun = uiIcon(PhSun, "Sun");
export const Tablet = uiIcon(PhDeviceTablet, "Tablet");
export const Tag = uiIcon(PhTag, "Tag");
export const Terminal = uiIcon(PhTerminal, "Terminal");
export const TestTube = uiIcon(PhTestTube, "TestTube");
export const Trash2 = uiIcon(PhTrash, "Trash2");
export const TriangleAlert = uiIcon(PhWarning, "TriangleAlert");
export const TriangleAlertIcon = uiIcon(PhWarning, "TriangleAlertIcon");
export const Type = uiIcon(PhTextT, "Type");
export const Undo2 = uiIcon(PhArrowUUpLeft, "Undo2");
export const Unlink = uiIcon(PhLinkBreak, "Unlink");
export const Upload = uiIcon(PhUploadSimple, "Upload");
export const UserRound = uiIcon(PhUser, "UserRound");
export const Workflow = uiIcon(PhFlowArrow, "Workflow");
export const WrapText = uiIcon(PhArrowUDownLeft, "WrapText");
export const Wrench = uiIcon(PhWrench, "Wrench");
export const X = uiIcon(PhX, "X");
export const XCircle = uiIcon(PhXCircle, "XCircle");
export const Zap = uiIcon(PhLightning, "Zap");
export const ZoomIn = uiIcon(PhMagnifyingGlassPlus, "ZoomIn");
export const ZoomOut = uiIcon(PhMagnifyingGlassMinus, "ZoomOut");
